name: rssblog source
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16,4,10 * * *'
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 1
          ref: master
      - name: Pull source dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 1
          ref: dev
      - name: Pull public
        uses: actions/checkout@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          persist-credentials: false
          fetch-depth: 1
          ref: public
          path: ./public
      - name: Pull public dev
        uses: actions/checkout@v2
        if: ${{ github.ref == 'refs/heads/dev' }}
        with:
          persist-credentials: false
          fetch-depth: 1
          ref: public-dev
          path: ./public
      - name: Check source
        shell: bash
        run: |
          rm -fr ./public/.git
          ls -lh ./
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Build source
        run: python action.py
      - name: Fix source
        run: python fixed.py ${{ secrets.FIXED_TYPE }}
      - name: Upload public
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull public
        uses: actions/checkout@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          persist-credentials: false
          fetch-depth: 1
          ref: public
      - name: Pull public dev
        uses: actions/checkout@v2
        if: ${{ github.ref == 'refs/heads/dev' }}
        with:
          persist-credentials: false
          fetch-depth: 1
          ref: public-dev
      - name: Clean public
        run: |
          rm -fr ./*
      - name: Download public
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: Check download
        shell: bash
        run: |
          ls -lh ./
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "daily update $(date +'%B %d, %Y %T (%Z)')" --allow-empty
      - name: Push changes
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
          force: true
      - name: Push changes dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: public-dev
          force: true

  # trigger:
  #   needs: deploy
  #   if: ${{ github.ref == 'refs/heads/master' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Vercel
  #       shell: bash
  #       run: |
  #         curl -X POST ${{ secrets.VERCEL_TRIGGER }}

  # sync:
  #   needs: deploy
  #   if: ${{ github.ref == 'refs/heads/master' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Sync Gitee
  #       uses: Yikun/hub-mirror-action@master
  #       with:
  #         src: github/caibingcheng
  #         dst: gitee/caibingcheng
  #         force_update: true
  #         dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
  #         dst_token: ${{ secrets.GITEE_TOKEN }}
  #         static_list: "rssblog-source"
